apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: spring-petclinic-tap
  annotations:
    github.com/project-slug: askanonymous/spring-petclinic-tap
spec:
  type: other
  lifecycle: unknown
  owner: Abhishek Singh
