apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"tekton.dev/v1beta1","kind":"Pipeline","metadata":{"annotations":{},"labels":{"apps.tanzu.vmware.com/pipeline":"test"},"name":"developer-defined-tekton-pipeline","namespace":"developer"},"spec":{"params":[{"name":"source-url"},{"name":"source-revision"}],"tasks":[{"name":"test","params":[{"name":"source-url","value":"$(params.source-url)"},{"name":"source-revision","value":"$(params.source-revision)"}],"taskSpec":{"params":[{"name":"source-url"},{"name":"source-revision"}],"steps":[{"image":"gradle","name":"test","script":"cd `mktemp -d`\nwget -qO- $(params.source-url) | tar xvz -m\nchmod +x mvnw\n./mvnw test"}]}}]}}
  creationTimestamp: "2023-09-21T18:49:57Z"
  generation: 1
  labels:
    apps.tanzu.vmware.com/pipeline: test
  name: developer-defined-tekton-pipeline
  namespace: developer
  resourceVersion: "7089482"
  uid: f861bf6f-956d-42d1-aa65-256c40a43ee8
spec:
  params:
  - name: source-url
    type: string
  - name: source-revision
    type: string
  tasks:
  - name: test
    params:
    - name: source-url
      value: $(params.source-url)
    - name: source-revision
      value: $(params.source-revision)
    taskSpec:
      metadata: {}
      params:
      - name: source-url
        type: string
      - name: source-revision
        type: string
      spec: null
      steps:
      - image: gradle
        name: test
        resources: {}
        script: |-
          cd `mktemp -d`
          wget -qO- $(params.source-url) | tar xvz -m
          # chmod +x mvnw
          ./mvnw test
